// <auto-generated />
using System;
using GenericCrud.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenericCrud.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707111945_inti")]
    partial class inti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenericCrud.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultSortColumn")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefaultSortDirection")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PageCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PageSize")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryKeyColumn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("SoftDeleteColumn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName")
                        .IsUnique();

                    b.ToTable("DynamicEntities");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionalOnFieldName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConditionalOnValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DynamicEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("DynamicFieldSectionId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FormOrder")
                        .HasColumnType("int");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ShowInForm")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInTable")
                        .HasColumnType("bit");

                    b.Property<int>("TableOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DynamicFieldSectionId");

                    b.HasIndex("DynamicEntityId", "FieldName")
                        .IsUnique();

                    b.ToTable("DynamicFields");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFieldOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DynamicFieldId")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DynamicFieldId");

                    b.ToTable("DynamicFieldOptions");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFieldSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DynamicEntityId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicEntityId");

                    b.ToTable("DynamicFieldSections");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFieldValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DynamicFieldId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("MaxFileSizeKb")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicFieldId")
                        .IsUnique();

                    b.ToTable("DynamicFieldValidations");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFileConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedExtensions")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DynamicFieldId")
                        .HasColumnType("int");

                    b.Property<int>("MaxSizeKb")
                        .HasColumnType("int");

                    b.Property<bool>("RenameToGuid")
                        .HasColumnType("bit");

                    b.Property<string>("SaveFolder")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicFieldId")
                        .IsUnique();

                    b.ToTable("DynamicFileConfigs");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicForeignKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DynamicFieldId")
                        .HasColumnType("int");

                    b.Property<string>("ForeignTableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrderByColumn")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TextColumn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ValueColumn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicFieldId")
                        .IsUnique();

                    b.ToTable("DynamicForeignKeys");
                });

            modelBuilder.Entity("GenericCrud.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GenericCrud.Models.Statuses", b =>
                {
                    b.Property<int>("StatusesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusesID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("LIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StatusesID");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicField", b =>
                {
                    b.HasOne("GenericCrud.Models.Dynamic.DynamicEntity", "DynamicEntity")
                        .WithMany("Fields")
                        .HasForeignKey("DynamicEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenericCrud.Models.Dynamic.DynamicFieldSection", "Section")
                        .WithMany("Fields")
                        .HasForeignKey("DynamicFieldSectionId");

                    b.Navigation("DynamicEntity");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFieldOption", b =>
                {
                    b.HasOne("GenericCrud.Models.Dynamic.DynamicField", "DynamicField")
                        .WithMany("Options")
                        .HasForeignKey("DynamicFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicField");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFieldSection", b =>
                {
                    b.HasOne("GenericCrud.Models.Dynamic.DynamicEntity", "DynamicEntity")
                        .WithMany("Sections")
                        .HasForeignKey("DynamicEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicEntity");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFieldValidation", b =>
                {
                    b.HasOne("GenericCrud.Models.Dynamic.DynamicField", "DynamicField")
                        .WithOne("Validation")
                        .HasForeignKey("GenericCrud.Models.Dynamic.DynamicFieldValidation", "DynamicFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicField");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFileConfig", b =>
                {
                    b.HasOne("GenericCrud.Models.Dynamic.DynamicField", "DynamicField")
                        .WithOne("FileConfig")
                        .HasForeignKey("GenericCrud.Models.Dynamic.DynamicFileConfig", "DynamicFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicField");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicForeignKey", b =>
                {
                    b.HasOne("GenericCrud.Models.Dynamic.DynamicField", "DynamicField")
                        .WithOne("ForeignKey")
                        .HasForeignKey("GenericCrud.Models.Dynamic.DynamicForeignKey", "DynamicFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicField");
                });

            modelBuilder.Entity("GenericCrud.Models.Employee", b =>
                {
                    b.HasOne("GenericCrud.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GenericCrud.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicEntity", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicField", b =>
                {
                    b.Navigation("FileConfig");

                    b.Navigation("ForeignKey");

                    b.Navigation("Options");

                    b.Navigation("Validation");
                });

            modelBuilder.Entity("GenericCrud.Models.Dynamic.DynamicFieldSection", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
